# Generated by Django 5.0.6 on 2024-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_type', models.CharField(choices=[('SPORT', 'sport'), ('RPG', 'rpg'), ('ADVENTURE', 'adventure'), ('FANTASY', 'fantasy')], max_length=20)),
                ('PS4', models.BooleanField(default=False)),
                ('PS5', models.BooleanField(default=False)),
                ('PC', models.BooleanField(default=False)),
                ('Multiplayer_mode', models.BooleanField(default=False)),
                ('games', models.CharField(choices=[('Final_Fantasy_X', 'Final Fantasy X'), ('Fifa_2024', 'Fifa 2024'), ('Spyro', 'spyro'), ('LEAGUE OF LEGENDS', 'League of Legends'), ('WORLD OF WARCRAFT', 'Word of Warcraft'), ('NBA_2024', 'NBA 2024'), ('Cyber_Punk', 'Cyber Punk')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
